<?php

namespace CG\PortfolioBundle\Repository;

/**
 * ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleRepository extends \Doctrine\ORM\EntityRepository
{
    public function getAllArticles()
    {
        return $qb = $this->createQueryBuilder('e')
                ->orderBy('e.dateCreation','DESC')
                ->getQuery()
                ->getResult();
    }
    
    public function getLastArticles()
    {
        return $qb = $this->createQueryBuilder('e')
                ->orderBy('e.dateCreation', 'DESC')
                ->setMaxResults(5)
                ->getQuery()
                ->getResult();
    }
}
