<?php

namespace CG\PortfolioBundle\Repository;

/**
 * EducationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EducationRepository extends \Doctrine\ORM\EntityRepository
{
    public function getAllEducations()
    {
        return $qb = $this->createQueryBuilder('e')
                ->orderBy('e.degree','DESC')
                ->getQuery()
                ->getResult();
    }
}
