<?php

namespace CG\PortfolioBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * MessageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MessageRepository extends EntityRepository
{
    public function getAllMessages($order = "ASC") {
        return $qb = $this->createQueryBuilder('m')
                     ->orderBy('m.date', $order)
                     ->getQuery()
                     ->getResult();
    }
}
