<?php

namespace CG\PortfolioBundle\Repository;

/**
 * SkillRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SkillRepository extends \Doctrine\ORM\EntityRepository
{
    public function getAllSkills() {
        return $qb = $this->createQueryBuilder('m')
                     ->getQuery()
                     ->getResult();
    }
    
}
